package com.quiz.quizgame.service;

import com.quiz.quizgame.cache.LRUCache;
import com.quiz.quizgame.model.Option;
import com.quiz.quizgame.model.Question;
import com.quiz.quizgame.model.Quiz;
import com.quiz.quizgame.repository.QuizRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.ArgumentMatchers.anyInt;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Optional;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class) // enables Mockito in this test class
class QuizServiceTest {

    // fake repository no real DynamoDB calls
    @Mock
    private QuizRepository quizRepository;
    // fake cache, no real cache operations
    @Mock
    private LRUCache lruCache;

    // @InjectMocks creates a real QuizService object but automatically injects the
    // fake quizRepository and lruCache into it
    @InjectMocks
    private QuizService quizService;

    // common test data used across tests
    private Quiz testQuiz;
    private Quiz dbQuiz;          // quiz fetched from DB on cache miss
    private Quiz invalidQuiz;     // quiz with non-existent id

    private Question testQuestion;
    private Question newQuestion;          // question to be added
    private Question updatedQuestion;      // question with updated data
    private Question nonExistentQuestion;  // question with invalid id

    private Option testOption;
    private Option newOption;              // option to be added
    private Option updatedOption;          // option with updated data
    private Option nonExistentOption;      // option with invalid id


    @BeforeEach
    void setUp() {
        //1)Option Objects
        //create testOption
        testOption = new Option();
        testOption.setId("Opt1");
        testOption.setQuestionId("Qn1");
        testOption.setText("8");
        testOption.setCorrect(true);

        // new option to be added to question (no id — auto generated by service)
        newOption = new Option();
        newOption.setText("9");
        newOption.setCorrect(false);

        // updated option with same id as testOption but new data
        updatedOption = new Option();
        updatedOption.setId("Opt1");   // same id as existing option
        updatedOption.setText("10");   // updated text
        updatedOption.setCorrect(false); // updated flag

        // option with non-existent id, used to test not found cases
        nonExistentOption = new Option();
        nonExistentOption.setId("INVALID-OPT");
        nonExistentOption.setText("Some text");

        //2)Ques objects:

        //create testQuestion
        testQuestion = new Question();
        testQuestion.setId("Qn1");
        testQuestion.setQuizId("Quiz1");
        testQuestion.setText("No of Planets?");
        testQuestion.setType("MCQ");
        testQuestion.setTimeLimit(30);
        //asList converts option to list but it returns fixed size list so we cant modify items in it
        //so wraps the fixed list inside a new ArrayList to add/remove items from it
        testQuestion.setOptionList(new ArrayList<>(Arrays.asList(testOption)));

        // new question to be added to quiz (no id — auto generated by service)
        newQuestion = new Question();
        newQuestion.setText("What is capital of France?");
        newQuestion.setType("MCQ");
        newQuestion.setTimeLimit(20);
        newQuestion.setOptionList(new ArrayList<>());

        // updated question with same id as testQuestion but new data
        // no optionList set — service should preserve existing options
        updatedQuestion = new Question();
        updatedQuestion.setId("Qn1");  // same id as existing question
        updatedQuestion.setText("How many moons does Earth have?"); // updated text
        updatedQuestion.setType("MCQ");
        updatedQuestion.setTimeLimit(60); // updated timeLimit

        // question with non-existent id — used to test not found cases
        nonExistentQuestion = new Question();
        nonExistentQuestion.setId("INVALID-QN");
        nonExistentQuestion.setText("Some text");

        //3)Quiz Objects

        // create test quiz with question inside
        testQuiz = new Quiz();
        testQuiz.setId("Quiz1");
        testQuiz.setName("Science Quiz");
        testQuiz.setMaxPlayers(10);
        testQuiz.setQuestionList(new ArrayList<>(Arrays.asList(testQuestion)));
        // quiz returned from DB on cache miss
        dbQuiz = new Quiz();
        dbQuiz.setId("Quiz2");
        dbQuiz.setName("Math Quiz");
        dbQuiz.setQuestionList(new ArrayList<>());

        // quiz with non-existent id — used to test not found cases
        invalidQuiz = new Quiz();
        invalidQuiz.setId("INVALID");
        invalidQuiz.setName("Invalid Quiz");
        invalidQuiz.setQuestionList(new ArrayList<>());



    }
    //1)Quiz Tests
    @Test
    void getQuizList_HappyCase_ReturnsAllQuizzes() {
        // arrange: fake repo returns list with testQuiz
        when(quizRepository.findAll()).thenReturn(Arrays.asList(testQuiz));

        // act
        List<Quiz> result = quizService.getQuizList();

        // assert: should have 1 quiz with correct name
        assertEquals(1, result.size());
        assertEquals("Science Quiz", result.get(0).getName());
        // verify: findAll called exactly once
        verify(quizRepository, times(1)).findAll();
    }

    @Test
    void getQuizList_EmptyDB_ReturnsEmptyList() {
        // arrange: fake repo returns empty list
        when(quizRepository.findAll()).thenReturn(new ArrayList<>());

        // act
        List<Quiz> result = quizService.getQuizList();

        // assert: empty list returned not null
        assertTrue(result.isEmpty());
    }
    @Test
    void test_getQuizById_LRUCacheHit_NoDBCall() {
        //Cache hit: return from cache without DB call
        //when quiz found in cache then return it
        when(lruCache.get("Quiz1")).thenReturn(testQuiz);
        Quiz cacheResult = quizService.getQuizById("Quiz1");
        //correct quiz returned from cache
        assertEquals("Quiz1", cacheResult.getId());
        //DB should never be called on cache hit
        verify(quizRepository, never()).findById(any());
    }

    @Test
    void test_getQuizById_CacheMiss_FetchesFromDB_SavestoCache() {
        // arrange: cache miss for Quiz2
        when(lruCache.get("Quiz2")).thenReturn(null);
        // DB returns dbQuiz for Quiz2
        when(quizRepository.findById("Quiz2")).thenReturn(Optional.of(dbQuiz));

        // act
        Quiz result = quizService.getQuizById("Quiz2");

        // assert: correct quiz returned from DB
        assertEquals("Quiz2", result.getId());
        // verify: quiz saved to cache after DB fetch
        verify(lruCache, times(1)).put("Quiz2", dbQuiz);
        // verify: DB was called once since cache missed
        verify(quizRepository, times(1)).findById("Quiz2");
    }

    @Test
    void test_addQuiz_GeneratesId_SavesToDB_PutsInCache() {
        // arrange: quiz without id (id should be auto generated)
        Quiz newQuiz = new Quiz();
        newQuiz.setName("New Quiz");
        newQuiz.setMaxPlayers(5);
        newQuiz.setQuestionList(null); // null to test null check
        // act
        quizService.addQuiz(newQuiz);

        // id should be auto generated not null
        assertNotNull(newQuiz.getId());
        // questionList should be set to empty list when null
        assertNotNull(newQuiz.getQuestionList());
        assertTrue(newQuiz.getQuestionList().isEmpty());
        // quiz saved to DB
        verify(quizRepository, times(1)).save(newQuiz);
        // quiz put in cache after save
        verify(lruCache, times(1)).put(newQuiz.getId(), newQuiz);
    }

    @Test
    void test_addQuiz_ExistingQuestionList_NotOverridden() {
        // arrange: dbQuiz already has empty questionList
        // add testQuestion to it to test preservation
        dbQuiz.setQuestionList(new ArrayList<>(Arrays.asList(testQuestion)));

        // act
        quizService.addQuiz(dbQuiz);

        // assert: existing questionList preserved not replaced with empty
        assertEquals(1, dbQuiz.getQuestionList().size());
    }

    @Test
    void test_updateQuiz_QuizExists_UpdatesDBAndCache() {
        // arrange: testQuiz exists in DB
        when(quizRepository.existsById("Quiz1")).thenReturn(true);

        // act
        quizService.updateQuiz(testQuiz);

        // verify: quiz saved to DB
        verify(quizRepository, times(1)).saveWithVersionCheck(eq(testQuiz), anyInt());
        // verify: cache updated directly with new data not evicted
        verify(lruCache, times(1)).put("Quiz1", testQuiz);
    }

    @Test
    void test_updateQuiz_QuizNotFound_ThrowsException() {
        // arrange: invalidQuiz does NOT exist in DB
        when(quizRepository.existsById("INVALID")).thenReturn(false);

        // act and assert: RuntimeException thrown
        RuntimeException exception = assertThrows(RuntimeException.class,
                () -> quizService.updateQuiz(invalidQuiz));

        // correct error message
        assertEquals("Quiz not found: INVALID", exception.getMessage());
        // save never called when quiz not found
        verify(quizRepository, never()).save(any());
        // cache never updated when quiz not found
        verify(lruCache, never()).put(any(), any());
    }

    @Test
    void test_deleteQuiz_QuizExists_DeletesFromDBAndEvictsCache() {
        // arrange: testQuiz exists in DB
        when(quizRepository.existsById("Quiz1")).thenReturn(true);

        // act
        quizService.deleteQuiz("Quiz1");

        // verify: quiz deleted from DB
        verify(quizRepository, times(1)).deleteById("Quiz1");
        // verify: cache evicted since quiz is gone (not put)
        verify(lruCache, times(1)).evict("Quiz1");
        // verify: cache put NEVER called on delete
        verify(lruCache, never()).put(any(), any());
    }

    @Test
    void test_deleteQuiz_QuizNotFound_ThrowsException() {
        // arrange: INVALID quiz does NOT exist in DB
        when(quizRepository.existsById("INVALID")).thenReturn(false);

        // act and assert: RuntimeException thrown
        RuntimeException exception = assertThrows(RuntimeException.class,
                () -> quizService.deleteQuiz("INVALID"));

        // correct error message
        assertEquals("Quiz not found: INVALID", exception.getMessage());
        // deleteById never called when quiz not found
        verify(quizRepository, never()).deleteById(any());
        // evict never called when quiz not found
        verify(lruCache, never()).evict(any());
    }

    //2) QUESTION TESTS

    @Test
    void test_getQuestionListByQuizId_QuizExists_ReturnsQuestionList() {
        // arrange: cache returns testQuiz which has testQuestion inside
        when(lruCache.get("Quiz1")).thenReturn(testQuiz);

        // act
        List<Question> result = quizService.getQuestionListByQuizId("Quiz1");

        // assert: 1 question returned with correct text
        assertEquals(1, result.size());
        assertEquals("No of Planets?", result.get(0).getText());
    }

    @Test
    void test_getQuestionListByQuizId_QuizNotFound_ReturnsEmptyList() {
        // arrange: cache miss and DB miss
        when(lruCache.get("INVALID")).thenReturn(null);
        when(quizRepository.findById("INVALID")).thenReturn(Optional.empty());

        // act
        List<Question> result = quizService.getQuestionListByQuizId("INVALID");

        // assert: empty list returned not null not exception
        assertTrue(result.isEmpty());
    }

    @Test
    void test_getQuestionById_QuestionExists_ReturnsQuestion() {
        // arrange: cache returns testQuiz which has testQuestion inside
        when(lruCache.get("Quiz1")).thenReturn(testQuiz);

        // act
        Question result = quizService.getQuestionById("Quiz1", "Qn1");

        // assert: correct question returned
        assertEquals("Qn1", result.getId());
        assertEquals("No of Planets?", result.getText());
    }

    @Test
    void test_getQuestionById_QuizNotFound_ReturnsNull() {
        // arrange: cache miss and DB miss
        when(lruCache.get("INVALID")).thenReturn(null);
        when(quizRepository.findById("INVALID")).thenReturn(Optional.empty());

        // act
        Question result = quizService.getQuestionById("INVALID", "Qn1");

        // assert: null returned — can't find question if quiz doesn't exist
        assertNull(result);
    }

    @Test
    void test_getQuestionById_QuestionNotFoundInQuiz_ReturnsNull() {
        // arrange: cache returns testQuiz
        // but nonExistentQuestion id doesn't exist in quiz
        when(lruCache.get("Quiz1")).thenReturn(testQuiz);

        // act
        Question result = quizService.getQuestionById("Quiz1", "INVALID-QN");

        // assert: null returned — quiz exists but question not inside it
        assertNull(result);
    }

    @Test
    void test_addQuestion_QuizExists_AddsQuestion_GeneratesId_UpdatesCache() {
        // arrange: cache returns testQuiz
        when(lruCache.get("Quiz1")).thenReturn(testQuiz);

        // assert before: quiz has 1 question
        assertEquals(1, testQuiz.getQuestionList().size());

        // act: add newQuestion to Quiz1
        quizService.addQuestion("Quiz1", newQuestion);

        // assert: id auto generated not null
        assertNotNull(newQuestion.getId());
        // assert: question linked to its quiz
        assertEquals("Quiz1", newQuestion.getQuizId());
        // assert: questionList grew from 1 to 2
        assertEquals(2, testQuiz.getQuestionList().size());
        // verify: quiz saved to DB with new question
        verify(quizRepository, times(1)).saveWithVersionCheck(eq(testQuiz), anyInt());
        // verify: cache updated with updated quiz directly
        verify(lruCache, times(1)).put("Quiz1", testQuiz);
    }

    @Test
    void test_addQuestion_QuizNotFound_ThrowsException() {
        // arrange: cache miss and DB miss
        when(lruCache.get("INVALID")).thenReturn(null);
        when(quizRepository.findById("INVALID")).thenReturn(Optional.empty());

        // act and assert: can't add question to non-existent quiz
        RuntimeException exception = assertThrows(RuntimeException.class,
                () -> quizService.addQuestion("INVALID", newQuestion));

        assertEquals("Quiz not found: INVALID", exception.getMessage());
        // save never called
        verify(quizRepository, never()).save(any());
        // cache never updated
        verify(lruCache, never()).put(any(), any());
    }

    @Test
    void test_updateQuestion_QuestionExists_UpdatesData_PreservesOptions() {
        // arrange: cache returns testQuiz
        when(lruCache.get("Quiz1")).thenReturn(testQuiz);

        // act: update testQuestion with updatedQuestion data
        quizService.updateQuestion("Quiz1", updatedQuestion);

        // assert: question text updated
        assertEquals("How many moons does Earth have?",
                testQuiz.getQuestionList().get(0).getText());
        // assert: timeLimit updated
        assertEquals(60, testQuiz.getQuestionList().get(0).getTimeLimit());
        // KEY assert: existing options preserved after update
        // updatedQuestion had no options but service copies them from old question
        assertEquals(1, testQuiz.getQuestionList().get(0).getOptionList().size());
        assertEquals("Opt1",
                testQuiz.getQuestionList().get(0).getOptionList().get(0).getId());
        // verify: quiz saved to DB
        verify(quizRepository, times(1)).saveWithVersionCheck(eq(testQuiz), anyInt());
        // verify: cache updated with updated quiz
        verify(lruCache, times(1)).put("Quiz1", testQuiz);
    }

    @Test
    void test_updateQuestion_QuizNotFound_ThrowsException() {
        // arrange: cache miss and DB miss
        when(lruCache.get("INVALID")).thenReturn(null);
        when(quizRepository.findById("INVALID")).thenReturn(Optional.empty());

        // act and assert: can't update question if quiz doesn't exist
        RuntimeException exception = assertThrows(RuntimeException.class,
                () -> quizService.updateQuestion("INVALID", testQuestion));

        assertEquals("Quiz not found: INVALID", exception.getMessage());
        verify(quizRepository, never()).save(any());
    }

    @Test
    void test_updateQuestion_QuestionNotFound_ThrowsException() {
        // arrange: cache returns testQuiz
        // nonExistentQuestion id doesn't match any question in testQuiz
        when(lruCache.get("Quiz1")).thenReturn(testQuiz);

        // act and assert
        RuntimeException exception = assertThrows(RuntimeException.class,
                () -> quizService.updateQuestion("Quiz1", nonExistentQuestion));

        assertEquals("Question not found: INVALID-QN", exception.getMessage());
        // save never called when question not found
        verify(quizRepository, never()).save(any());
        // cache never updated when question not found
        verify(lruCache, never()).put(any(), any());
    }

    @Test
    void test_deleteQuestion_QuestionExists_RemovesFromQuiz_UpdatesCache() {
        // arrange: cache returns testQuiz with 1 question
        when(lruCache.get("Quiz1")).thenReturn(testQuiz);

        // assert before: quiz has 1 question
        assertEquals(1, testQuiz.getQuestionList().size());

        // act
        quizService.deleteQuestion("Quiz1", "Qn1");

        // assert after: questionList empty — question removed
        assertEquals(0, testQuiz.getQuestionList().size());
        // verify: quiz saved to DB with question removed
        verify(quizRepository, times(1)).saveWithVersionCheck(eq(testQuiz), anyInt());
        // verify: cache updated with updated quiz (not evicted)
        verify(lruCache, times(1)).put("Quiz1", testQuiz);
    }

    @Test
    void test_deleteQuestion_QuizNotFound_ThrowsException() {
        // arrange: cache miss and DB miss
        when(lruCache.get("INVALID")).thenReturn(null);
        when(quizRepository.findById("INVALID")).thenReturn(Optional.empty());

        // act and assert
        RuntimeException exception = assertThrows(RuntimeException.class,
                () -> quizService.deleteQuestion("INVALID", "Qn1"));

        assertEquals("Quiz not found: INVALID", exception.getMessage());
        verify(quizRepository, never()).save(any());
    }

    @Test
    void test_deleteQuestion_QuestionNotFound_ThrowsException() {
        // arrange: cache returns testQuiz
        // INVALID-QN doesn't exist in quiz's questionList
        when(lruCache.get("Quiz1")).thenReturn(testQuiz);

        // act and assert
        RuntimeException exception = assertThrows(RuntimeException.class,
                () -> quizService.deleteQuestion("Quiz1", "INVALID-QN"));

        assertEquals("Question not found: INVALID-QN", exception.getMessage());
        verify(quizRepository, never()).save(any());
        verify(lruCache, never()).put(any(), any());
    }

    //3)OPTION TESTS ────────────────────────────────────────────────────────

    @Test
    void test_getOptionListByQuestionId_QuestionExists_ReturnsOptionList() {
        // arrange: cache returns testQuiz which has testQuestion with testOption
        when(lruCache.get("Quiz1")).thenReturn(testQuiz);

        // act
        List<Option> result = quizService.getOptionListByQuestionId("Quiz1", "Qn1");

        // assert: 1 option returned with correct text
        assertEquals(1, result.size());
        assertEquals("8", result.get(0).getText());
    }

    @Test
    void test_getOptionListByQuestionId_QuestionNotFound_ReturnsEmptyList() {
        // arrange: cache returns testQuiz
        // but INVALID-QN doesn't exist in quiz
        when(lruCache.get("Quiz1")).thenReturn(testQuiz);

        // act
        List<Option> result = quizService.getOptionListByQuestionId("Quiz1", "INVALID-QN");

        // assert: empty list returned not null not exception
        assertTrue(result.isEmpty());
    }

    @Test
    void test_getOptionById_OptionExists_ReturnsOption() {
        // arrange: cache returns testQuiz which has testQuestion with testOption
        when(lruCache.get("Quiz1")).thenReturn(testQuiz);

        // act
        Option result = quizService.getOptionById("Quiz1", "Qn1", "Opt1");

        // assert: correct option returned
        assertEquals("Opt1", result.getId());
        assertEquals("8", result.getText());
        assertTrue(result.isCorrect());
    }

    @Test
    void test_getOptionById_QuestionNotFound_ReturnsNull() {
        // arrange: cache returns testQuiz
        // but INVALID-QN doesn't exist in quiz
        when(lruCache.get("Quiz1")).thenReturn(testQuiz);

        // act
        Option result = quizService.getOptionById("Quiz1", "INVALID-QN", "Opt1");

        // assert: null returned — can't find option if question doesn't exist
        assertNull(result);
    }

    @Test
    void test_getOptionById_OptionNotFound_ReturnsNull() {
        // arrange: cache returns testQuiz
        // question exists but INVALID-OPT doesn't exist
        when(lruCache.get("Quiz1")).thenReturn(testQuiz);

        // act
        Option result = quizService.getOptionById("Quiz1", "Qn1", "INVALID-OPT");

        // assert: null returned — question exists but option not inside it
        assertNull(result);
    }

    @Test
    void test_addOption_QuestionExists_AddsOption_GeneratesId_UpdatesCache() {
        // arrange: cache returns testQuiz
        when(lruCache.get("Quiz1")).thenReturn(testQuiz);

        // assert before: question has 1 option
        assertEquals(1, testQuestion.getOptionList().size());

        // act: add newOption to question Qn1
        quizService.addOption("Quiz1", "Qn1", newOption);

        // assert: option id auto generated not null
        assertNotNull(newOption.getId());
        // assert: option linked to its question
        assertEquals("Qn1", newOption.getQuestionId());
        // assert: optionList grew from 1 to 2
        assertEquals(2, testQuestion.getOptionList().size());
        // verify: quiz saved to DB
        verify(quizRepository, times(1)).saveWithVersionCheck(eq(testQuiz), anyInt());
        // verify: cache updated with updated quiz
        verify(lruCache, times(1)).put("Quiz1", testQuiz);
    }

    @Test
    void test_addOption_QuizNotFound_ThrowsException() {
        // arrange: cache miss and DB miss
        when(lruCache.get("INVALID")).thenReturn(null);
        when(quizRepository.findById("INVALID")).thenReturn(Optional.empty());

        // act and assert: can't add option if quiz doesn't exist
        RuntimeException exception = assertThrows(RuntimeException.class,
                () -> quizService.addOption("INVALID", "Qn1", newOption));

        assertEquals("Quiz not found: INVALID", exception.getMessage());
        verify(quizRepository, never()).save(any());
        verify(lruCache, never()).put(any(), any());
    }

    @Test
    void test_addOption_QuestionNotFound_ThrowsException() {
        // arrange: cache returns testQuiz
        // but INVALID-QN doesn't exist in quiz
        when(lruCache.get("Quiz1")).thenReturn(testQuiz);

        // act and assert: can't add option if question doesn't exist
        RuntimeException exception = assertThrows(RuntimeException.class,
                () -> quizService.addOption("Quiz1", "INVALID-QN", newOption));

        assertEquals("Question not found: INVALID-QN", exception.getMessage());
        verify(quizRepository, never()).save(any());
        verify(lruCache, never()).put(any(), any());
    }

    @Test
    void test_updateOption_OptionExists_UpdatesData_SavestoCache() {
        // arrange: cache returns testQuiz
        when(lruCache.get("Quiz1")).thenReturn(testQuiz);

        // act: update testOption with updatedOption data
        quizService.updateOption("Quiz1", "Qn1", updatedOption);

        // assert: option text updated
        assertEquals("10", testQuestion.getOptionList().get(0).getText());
        // assert: correct flag updated
        assertFalse(testQuestion.getOptionList().get(0).isCorrect());
        // verify: quiz saved to DB
        verify(quizRepository, times(1)).saveWithVersionCheck(eq(testQuiz), anyInt());
        // verify: cache updated with updated quiz
        verify(lruCache, times(1)).put("Quiz1", testQuiz);
    }

    @Test
    void test_updateOption_QuizNotFound_ThrowsException() {
        // arrange: cache miss and DB miss
        when(lruCache.get("INVALID")).thenReturn(null);
        when(quizRepository.findById("INVALID")).thenReturn(Optional.empty());

        // act and assert
        RuntimeException exception = assertThrows(RuntimeException.class,
                () -> quizService.updateOption("INVALID", "Qn1", updatedOption));

        assertEquals("Quiz not found: INVALID", exception.getMessage());
        verify(quizRepository, never()).save(any());
    }

    @Test
    void test_updateOption_QuestionNotFound_ThrowsException() {
        // arrange: cache returns testQuiz
        // INVALID-QN doesn't exist in quiz
        when(lruCache.get("Quiz1")).thenReturn(testQuiz);

        // act and assert
        RuntimeException exception = assertThrows(RuntimeException.class,
                () -> quizService.updateOption("Quiz1", "INVALID-QN", updatedOption));

        assertEquals("Question not found: INVALID-QN", exception.getMessage());
        verify(quizRepository, never()).save(any());
    }

    @Test
    void test_updateOption_OptionNotFound_ThrowsException() {
        // arrange: cache returns testQuiz
        // nonExistentOption id doesn't match any option in testQuestion
        when(lruCache.get("Quiz1")).thenReturn(testQuiz);

        // act and assert
        RuntimeException exception = assertThrows(RuntimeException.class,
                () -> quizService.updateOption("Quiz1", "Qn1", nonExistentOption));

        assertEquals("Option not found: INVALID-OPT", exception.getMessage());
        verify(quizRepository, never()).save(any());
        verify(lruCache, never()).put(any(), any());
    }

    @Test
    void test_deleteOption_OptionExists_RemovesFromQuestion_UpdatesCache() {
        // arrange: cache returns testQuiz
        when(lruCache.get("Quiz1")).thenReturn(testQuiz);

        // assert before: question has 1 option
        assertEquals(1, testQuestion.getOptionList().size());

        // act
        quizService.deleteOption("Quiz1", "Qn1", "Opt1");

        // assert after: optionList empty — option removed
        assertEquals(0, testQuestion.getOptionList().size());
        // verify: quiz saved to DB with option removed
        verify(quizRepository, times(1)).saveWithVersionCheck(eq(testQuiz), anyInt());
        // verify: cache updated with updated quiz (not evicted)
        verify(lruCache, times(1)).put("Quiz1", testQuiz);
    }

    @Test
    void test_deleteOption_QuizNotFound_ThrowsException() {
        // arrange: cache miss and DB miss
        when(lruCache.get("INVALID")).thenReturn(null);
        when(quizRepository.findById("INVALID")).thenReturn(Optional.empty());

        // act and assert
        RuntimeException exception = assertThrows(RuntimeException.class,
                () -> quizService.deleteOption("INVALID", "Qn1", "Opt1"));

        assertEquals("Quiz not found: INVALID", exception.getMessage());
        verify(quizRepository, never()).save(any());
    }

    @Test
    void test_deleteOption_QuestionNotFound_ThrowsException() {
        // arrange: cache returns testQuiz
        // INVALID-QN doesn't exist in quiz
        when(lruCache.get("Quiz1")).thenReturn(testQuiz);

        // act and assert
        RuntimeException exception = assertThrows(RuntimeException.class,
                () -> quizService.deleteOption("Quiz1", "INVALID-QN", "Opt1"));

        assertEquals("Question not found: INVALID-QN", exception.getMessage());
        verify(quizRepository, never()).save(any());
    }

    @Test
    void test_deleteOption_OptionNotFound_ThrowsException() {
        // arrange: cache returns testQuiz
        // INVALID-OPT doesn't exist in question
        when(lruCache.get("Quiz1")).thenReturn(testQuiz);

        // act and assert
        RuntimeException exception = assertThrows(RuntimeException.class,
                () -> quizService.deleteOption("Quiz1", "Qn1", "INVALID-OPT"));

        assertEquals("Option not found: INVALID-OPT", exception.getMessage());
        verify(quizRepository, never()).save(any());
        verify(lruCache, never()).put(any(), any());
    }
}
